on:
  workflow_dispatch:

jobs:
  demo:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [latest, "lts/*"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version:  ${{ matrix.node }}
      - run: node --version          
      - run: npm --version          
      - uses: actions/checkout@v3          
      - run: ./test.sh
        shell: bash
